import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useDispatch } from "react-redux";
import { uiControlsActions } from "@/redux/ui-controls-reducer";
import APIClient from "@/utils/api-client";
import ResponsiveAppBar from "@/components/common/top-navbar";
const { RxUpdateTheme } = uiControlsActions;
import Button from "@mui/material/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const dispatch = useDispatch();

  const toggleThemeInRedux = () => {
    APIClient({
      route: "/notif/read/2",
      method: "GET",
      payload: {},
      headers: {},
      successFn: () => {},
      errorFn: (err) => {},
      finallyFn: () => {},
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ResponsiveAppBar />
      <button onClick={toggleThemeInRedux}> Toggle Theme </button>
      <Button color="secondary" onClick={toggleThemeInRedux}>
        MUI Button
      </Button>
    </>
  );
}
